[package]
name = "weather"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version= "1.0.217", features=["blocking", "json"]}
reqwest = {version = "1.0", features = ["derivative"]}
serde_json = "1.0"
colored = "2.0"